### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Saleh7/laravel-au-zsh-plugin#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by Saleh7** [comment]
@unixorn 
done , Thank you

https://github.com/Saleh7/laravel-au-zsh-plugin/blob/master/LICENSE.md

**Comment by unixorn** [comment]
You're welcome, adding in https://github.com/unixorn/awesome-zsh-plugins/pull/817
